/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ALLOWED_THEMES: typeof import('./src/composables/useTheme').ALLOWED_THEMES
  const COMPONENT_FORM: typeof import('./src/constants/index').COMPONENT_FORM
  const COMPONENT_FORM_META: typeof import('./src/constants/index').COMPONENT_FORM_META
  const COMPONENT_LIST: typeof import('./src/constants/index').COMPONENT_LIST
  const COMPONENT_STORE_MAP: typeof import('./src/db/index').COMPONENT_STORE_MAP
  const COMPONENT_TYPO: typeof import('./src/constants/index').COMPONENT_TYPO
  const COMPONENT_TYPOGRAPHY_META: typeof import('./src/constants/index').COMPONENT_TYPOGRAPHY_META
  const ComboUXDatabase: typeof import('./src/db/index').ComboUXDatabase
  const D: typeof import('./src/composables/useDualModePatch').D
  const EXPORT_KEY_MAP: typeof import('./src/db/index').EXPORT_KEY_MAP
  const EffectScope: typeof import('vue').EffectScope
  const FieldContextKey: typeof import('vee-validate').FieldContextKey
  const FormContextKey: typeof import('vee-validate').FormContextKey
  const THEME_CHANGE_EVENT: typeof import('./src/composables/useTheme').THEME_CHANGE_EVENT
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const computed: typeof import('vue').computed
  const configure: typeof import('vee-validate').configure
  const createApp: typeof import('vue').createApp
  const createComponentStore: typeof import('./src/composables/useComponentStoreFactory').createComponentStore
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const db: typeof import('./src/db/index').db
  const deepClone: typeof import('./src/composables/useVariantManager').deepClone
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineRule: typeof import('vee-validate').defineRule
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const generateFontUrl: typeof import('./src/composables/googleFonts').generateFontUrl
  const generateReadme: typeof import('./src/composables/useReadmeGenerator').generateReadme
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFormsDefaults: typeof import('./src/stores/forms').getFormsDefaults
  const getOrCreatePersistence: typeof import('./src/composables/usePersistence').getOrCreatePersistence
  const getTypographyDefaults: typeof import('./src/stores/typography').getTypographyDefaults
  const h: typeof import('vue').h
  const initTheme: typeof import('./src/composables/useTheme').initTheme
  const inject: typeof import('vue').inject
  const injectFontLink: typeof import('./src/composables/googleFonts').injectFontLink
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isThemeComponentData: typeof import('./src/types/theme').isThemeComponentData
  const loadFontsFromVariant: typeof import('./src/composables/useGoogleFonts').loadFontsFromVariant
  const loadFontsFromVariants: typeof import('./src/composables/useGoogleFonts').loadFontsFromVariants
  const loadGoogleFont: typeof import('./src/composables/useGoogleFonts').loadGoogleFont
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeManager: typeof import('./src/composables/useStoreManager').storeManager
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAccordionStore: typeof import('./src/stores/accordion').useAccordionStore
  const useAlertStore: typeof import('./src/stores/alert').useAlertStore
  const useAttrs: typeof import('vue').useAttrs
  const useAvatarStore: typeof import('./src/stores/avatar').useAvatarStore
  const useBadgeStore: typeof import('./src/stores/badge').useBadgeStore
  const useButtonStore: typeof import('./src/stores/button').useButtonStore
  const useCardStore: typeof import('./src/stores/card').useCardStore
  const useChipStore: typeof import('./src/stores/chip').useChipStore
  const useComponentRegistry: typeof import('./src/composables/useComponentRegistry').useComponentRegistry
  const useComponentTheme: typeof import('./src/composables/useComponentTheme').useComponentTheme
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDarkStyles: typeof import('./src/composables/useDarkStyles').useDarkStyles
  const useDividerStore: typeof import('./src/stores/divider').useDividerStore
  const useDualModePatch: typeof import('./src/composables/useDualModePatch').useDualModePatch
  const useField: typeof import('vee-validate').useField
  const useFieldArray: typeof import('vee-validate').useFieldArray
  const useFieldError: typeof import('vee-validate').useFieldError
  const useFieldValue: typeof import('vee-validate').useFieldValue
  const useForm: typeof import('vee-validate').useForm
  const useFormErrors: typeof import('vee-validate').useFormErrors
  const useFormValues: typeof import('vee-validate').useFormValues
  const useFormsPersistence: typeof import('./src/composables/useFormsPersistence').useFormsPersistence
  const useFormsStore: typeof import('./src/stores/forms').useFormsStore
  const useGoogleFonts: typeof import('./src/composables/useGoogleFonts').default
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useIsFieldDirty: typeof import('vee-validate').useIsFieldDirty
  const useIsFieldTouched: typeof import('vee-validate').useIsFieldTouched
  const useIsFieldValid: typeof import('vee-validate').useIsFieldValid
  const useIsFormDirty: typeof import('vee-validate').useIsFormDirty
  const useIsFormTouched: typeof import('vee-validate').useIsFormTouched
  const useIsFormValid: typeof import('vee-validate').useIsFormValid
  const useIsSubmitting: typeof import('vee-validate').useIsSubmitting
  const useListGroupStore: typeof import('./src/stores/listgroup').useListGroupStore
  const useModel: typeof import('vue').useModel
  const useNavigationStore: typeof import('./src/stores/navigation').useNavigationStore
  const usePaginationStore: typeof import('./src/stores/pagination').usePaginationStore
  const usePersistence: typeof import('./src/composables/usePersistence').usePersistence
  const usePreviewGrid: typeof import('./src/composables/usePreviewGrid').usePreviewGrid
  const useProgressStore: typeof import('./src/stores/progress').useProgressStore
  const useResetForm: typeof import('vee-validate').useResetForm
  const useSlots: typeof import('vue').useSlots
  const useSpinnerStore: typeof import('./src/stores/spinner').useSpinnerStore
  const useStoreManager: typeof import('./src/composables/useStoreManager').useStoreManager
  const useStyleBuilder: typeof import('./src/composables/useStyleBuilder').useStyleBuilder
  const useSubmitCount: typeof import('vee-validate').useSubmitCount
  const useSubmitForm: typeof import('vee-validate').useSubmitForm
  const useTableStore: typeof import('./src/stores/table').useTableStore
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('./src/composables/useTheme').useTheme
  const useThemeCompensation: typeof import('./src/composables/useThemeCompensation').useThemeCompensation
  const useThemeIO: typeof import('./src/composables/useThemeIO').useThemeIO
  const useThemeStore: typeof import('./src/stores/theme').useThemeStore
  const useThemeSync: typeof import('./src/composables/useThemeSync').useThemeSync
  const useThemeSyncLog: typeof import('./src/composables/useThemeSyncLog').useThemeSyncLog
  const useTooltipStore: typeof import('./src/stores/tooltip').useTooltipStore
  const useTypographyPersistence: typeof import('./src/composables/useTypographyPersistence').useTypographyPersistence
  const useTypographyStore: typeof import('./src/stores/typography').useTypographyStore
  const useUnitNumberUpdates: typeof import('./src/composables/useUnitNumberUpdates').useUnitNumberUpdates
  const useValidateField: typeof import('vee-validate').useValidateField
  const useValidateForm: typeof import('vee-validate').useValidateForm
  const useVariantManager: typeof import('./src/composables/useVariantManager').useVariantManager
  const useVariantPatch: typeof import('./src/composables/useVariantPatch').useVariantPatch
  const vWheelNumber: typeof import('./src/directives/wheelNumber').vWheelNumber
  const validate: typeof import('vee-validate').validate
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ComponentThemeOptions } from './src/composables/useComponentTheme'
  import('./src/composables/useComponentTheme')
  // @ts-ignore
  export type { DarkStyleConfig } from './src/composables/useDarkStyles'
  import('./src/composables/useDarkStyles')
  // @ts-ignore
  export type { DualModePatchOptions } from './src/composables/useDualModePatch'
  import('./src/composables/useDualModePatch')
  // @ts-ignore
  export type { GoogleFont } from './src/composables/useGoogleFonts'
  import('./src/composables/useGoogleFonts')
  // @ts-ignore
  export type { Theme } from './src/composables/useTheme'
  import('./src/composables/useTheme')
  // @ts-ignore
  export type { ThemeCompensation } from './src/composables/useThemeCompensation'
  import('./src/composables/useThemeCompensation')
  // @ts-ignore
  export type { LogEntry } from './src/composables/useThemeSyncLog'
  import('./src/composables/useThemeSyncLog')
  // @ts-ignore
  export type { BaseVariant } from './src/composables/useVariantManager'
  import('./src/composables/useVariantManager')
  // @ts-ignore
  export type { VariantPatchOptions } from './src/composables/useVariantPatch'
  import('./src/composables/useVariantPatch')
  // @ts-ignore
  export type { ListComponentMeta } from './src/constants/index'
  import('./src/constants/index')
  // @ts-ignore
  export type { AccordionVariant, DarkAccordion } from './src/types/accordion'
  import('./src/types/accordion')
  // @ts-ignore
  export type { AlertVariant, DarkAlert } from './src/types/alert'
  import('./src/types/alert')
  // @ts-ignore
  export type { AvatarOnline, AvatarVariant, DarkAvatar } from './src/types/avatar'
  import('./src/types/avatar')
  // @ts-ignore
  export type { BadgeVariant, DarkBadge } from './src/types/badge'
  import('./src/types/badge')
  // @ts-ignore
  export type { ButtonVariant, DarkButton } from './src/types/button'
  import('./src/types/button')
  // @ts-ignore
  export type { CardVariant, DarkCard } from './src/types/card'
  import('./src/types/card')
  // @ts-ignore
  export type { ChipVariant, DarkChip } from './src/types/chip'
  import('./src/types/chip')
  // @ts-ignore
  export type { DividerWidthValue, DividerVariant, DarkDivider } from './src/types/divider'
  import('./src/types/divider')
  // @ts-ignore
  export type { FormsVariantName, OptionOrientation, FormState, FormsGlobalConfig, DarkFormsGlobalConfig, FormsVariant, FormsVariants } from './src/types/forms'
  import('./src/types/forms')
  // @ts-ignore
  export type { BorderStyle, TreeUnit, FourUnit, LineHeightUnit, FontSizeUnit, LetterSpacingUnit, PaddingUnit, FontStyle, TextTransform, TextDecoration, TextAlign, ProgressType, SkeletonAnimation, SpinnerType, Position, BorderValue, BorderRadiusValue, PaddingValue, UnitNumber, LetterSpacingValue, ShadowValue, ComponentShadows, DarkModeShadows } from './src/types/generics'
  import('./src/types/generics')
  // @ts-ignore
  export type { ListGroupFlush, ListGroupNumbered, ListGroupVariant, DarkListGroup } from './src/types/listgroup'
  import('./src/types/listgroup')
  // @ts-ignore
  export type { PaginationVariant, DarkPagination } from './src/types/pagination'
  import('./src/types/pagination')
  // @ts-ignore
  export type { ProgressVariant, DarkProgress } from './src/types/progress'
  import('./src/types/progress')
  // @ts-ignore
  export type { SkeletonVariant, DarkSkeleton } from './src/types/skeleton'
  import('./src/types/skeleton')
  // @ts-ignore
  export type { SpinnerVariant, DarkSpinner } from './src/types/spinner'
  import('./src/types/spinner')
  // @ts-ignore
  export type { TableVariant, DarkTable } from './src/types/table'
  import('./src/types/table')
  // @ts-ignore
  export type { ThemeComponentData, ThemeTypographyData, ThemeFormsData, ThemeData } from './src/types/theme'
  import('./src/types/theme')
  // @ts-ignore
  export type { DarkTooltip, TooltipPlacement, TooltipVariant } from './src/types/tooltip'
  import('./src/types/tooltip')
  // @ts-ignore
  export type { TypographyVariantName, TypographyValue, DarkTypographyValue, TypographyGlobalConfig, TypographyVariant, TypographyVariants } from './src/types/typography'
  import('./src/types/typography')
  // @ts-ignore
  export type { ComboUXDatabase, ComponentData, TypographyData, FormsData, ThemeMetaData } from './src/db/index'
  import('./src/db/index')
}
