/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/previews/Alert.vue')['default']
    AlertPositionField: typeof import('./src/components/settings/fields/AlertPositionField.vue')['default']
    AlertSettings: typeof import('./src/components/settings/AlertSettings.vue')['default']
    Avatar: typeof import('./src/components/previews/Avatar.vue')['default']
    AvatarSettings: typeof import('./src/components/settings/AvatarSettings.vue')['default']
    BackgroundSwatch: typeof import('./src/components/settings/fields/BackgroundSwatch.vue')['default']
    Badge: typeof import('./src/components/previews/Badge.vue')['default']
    BadgeSettings: typeof import('./src/components/settings/BadgeSettings.vue')['default']
    BaseFields: typeof import('./src/components/shared/BaseFields.vue')['default']
    BorderField: typeof import('./src/components/settings/fields/BorderField.vue')['default']
    BorderRadiusField: typeof import('./src/components/settings/fields/BorderRadiusField.vue')['default']
    Button: typeof import('./src/components/previews/Button.vue')['default']
    ButtonSettings: typeof import('./src/components/settings/ButtonSettings.vue')['default']
    Card: typeof import('./src/components/previews/Card.vue')['default']
    CardSettings: typeof import('./src/components/settings/CardSettings.vue')['default']
    Chip: typeof import('./src/components/previews/Chip.vue')['default']
    ChipSettings: typeof import('./src/components/settings/ChipSettings.vue')['default']
    ColorField: typeof import('./src/components/settings/fields/ColorField.vue')['default']
    ConfirmModal: typeof import('./src/components/shared/ConfirmModal.vue')['default']
    CoverView: typeof import('./src/components/layout/CoverView.vue')['default']
    DarkModeShadowsSettings: typeof import('./src/components/settings/DarkModeShadowsSettings.vue')['default']
    Divider: typeof import('./src/components/previews/Divider.vue')['default']
    DividerSettings: typeof import('./src/components/settings/DividerSettings.vue')['default']
    FontFamilyField: typeof import('./src/components/settings/fields/FontFamilyField.vue')['default']
    FontSizeField: typeof import('./src/components/settings/fields/FontSizeField.vue')['default']
    Forms: typeof import('./src/components/previews/Forms.vue')['default']
    FormsSettings: typeof import('./src/components/settings/FormsSettings.vue')['default']
    GoBack: typeof import('./src/components/layout/GoBack.vue')['default']
    InteractiveFields: typeof import('./src/components/shared/InteractiveFields.vue')['default']
    LetterSpacingField: typeof import('./src/components/settings/fields/LetterSpacingField.vue')['default']
    ListGroup: typeof import('./src/components/previews/ListGroup.vue')['default']
    ListGroupSettings: typeof import('./src/components/settings/ListGroupSettings.vue')['default']
    MainBar: typeof import('./src/components/layout/MainBar.vue')['default']
    NumberUnitField: typeof import('./src/components/settings/fields/NumberUnitField.vue')['default']
    PaddingField: typeof import('./src/components/settings/fields/PaddingField.vue')['default']
    PreviewBackgroundPicker: typeof import('./src/components/shared/PreviewBackgroundPicker.vue')['default']
    PreviewView: typeof import('./src/components/layout/PreviewView.vue')['default']
    Progress: typeof import('./src/components/previews/Progress.vue')['default']
    ProgressSettings: typeof import('./src/components/settings/ProgressSettings.vue')['default']
    SettingsSection: typeof import('./src/components/settings/fields/SettingsSection.vue')['default']
    ShadowField: typeof import('./src/components/settings/fields/ShadowField.vue')['default']
    SidePanel: typeof import('./src/components/layout/SidePanel.vue')['default']
    SimpleShadowField: typeof import('./src/components/settings/fields/SimpleShadowField.vue')['default']
    Spinner: typeof import('./src/components/previews/Spinner.vue')['default']
    SpinnerSettings: typeof import('./src/components/settings/SpinnerSettings.vue')['default']
    SwitchField: typeof import('./src/components/settings/fields/SwitchField.vue')['default']
    Table: typeof import('./src/components/previews/Table.vue')['default']
    TableSettings: typeof import('./src/components/settings/TableSettings.vue')['default']
    TextAlignField: typeof import('./src/components/settings/fields/TextAlignField.vue')['default']
    ThemeSyncToggle: typeof import('./src/components/layout/ThemeSyncToggle.vue')['default']
    ThemeToggle: typeof import('./src/components/shared/ThemeToggle.vue')['default']
    Typography: typeof import('./src/components/previews/Typography.vue')['default']
    TypographyFields: typeof import('./src/components/shared/TypographyFields.vue')['default']
    TypographySettings: typeof import('./src/components/settings/TypographySettings.vue')['default']
    VariantHeader: typeof import('./src/components/settings/VariantHeader.vue')['default']
  }
}
